// <auto-generated />
using System;
using ERP_Latest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERP_Latest.Migrations
{
    [DbContext(typeof(ERP_LatestContext))]
    [Migration("20230913085051_Student_Details_Updated")]
    partial class Student_Details_Updated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ERP_Latest.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"), 1L, 1);

                    b.Property<string>("CourseCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SemesterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("CourseId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("ERP_Latest.Models.Student_Details", b =>
                {
                    b.Property<int>("StudentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentDetailId"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<string>("StudentAlternateEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("StudentAlternateMobile")
                        .HasColumnType("bigint");

                    b.Property<int>("StudentBatch")
                        .HasColumnType("int");

                    b.Property<string>("StudentBloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentCategory")
                        .HasColumnType("int");

                    b.Property<int>("StudentCetRank")
                        .HasColumnType("int");

                    b.Property<int?>("StudentCetType")
                        .HasColumnType("int");

                    b.Property<int>("StudentCommunity")
                        .HasColumnType("int");

                    b.Property<string>("StudentCurrentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StudentDob")
                        .HasColumnType("datetime2");

                    b.Property<long>("StudentFatherMobile")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentFatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<bool?>("StudentIsMgmt")
                        .HasColumnType("bit");

                    b.Property<bool?>("StudentIsOutDelhi")
                        .HasColumnType("bit");

                    b.Property<long>("StudentMotherMobile")
                        .HasColumnType("bigint");

                    b.Property<string>("StudentMotherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPermanentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhoto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentPreviousSchoolDetails")
                        .HasColumnType("int");

                    b.Property<int>("StudentProgramme")
                        .HasColumnType("int");

                    b.Property<int?>("StudentShift")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("StudentDetailId");

                    b.ToTable("Student_Details");
                });
#pragma warning restore 612, 618
        }
    }
}
